"""add tenant api key hash

Revision ID: eefa458984e2
Revises: fcf281176d15
Create Date: 2026-08-09 22:48:53.029417

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eefa458984e2'
down_revision: Union[str, Sequence[str], None] = 'fcf281176d15'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tenants', sa.Column('api_key_hash', sa.String(length=255), nullable=False))
    op.create_unique_constraint(None, 'tenants', ['api_key_hash'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tenants', type_='unique')
    op.drop_column('tenants', 'api_key_hash')
    # ### end Alembic commands ###
